### ISSUE TITLE
caranya cancel request

### ISSUE THREAD

**Issue by choiruru** [zetbaitsu/Benih#1]
Benih ini sangat bagus dan mudah diimplementasikan. tapi saya ada kendala ketika ingin cancel API request. Gimana caranya cancel API request..??
makasih.

**Comment by zetbaitsu** [comment]
@choiruru untuk cancel request retrofit 1.9 belum support.. di versi 2 baru support, tapi masih dalam tahap beta, mungkin nanti saya bisa implementasi ke benih selanjutnya...

ada cara lain yang bisa digunakan, yaitu melakukan unsubscribe ke rxjava nya, walaupun sebenarnya requestnya tetap jalan... hanya saja kode di subscriber.onNext nya yg tidak akan dipanggil, jadi hasil requestnya akan diabaikan...

untuk implementasinya kita bisa edit kode di presenter untuk mengembalikan Subscription... misalnya

#Presenter

``` java
public class BeritaPresenter extends BenihPresenter<BeritaPresenter.View> {

    public BeritaPresenter(View view) {
        super(view);
    }

    public Subscription loadListBerita() {
        return TaniPediaService.pluck()
                    .getApi()
                    .getAllBerita()
                    .compose(BenihScheduler.pluck().applySchedulers(BenihScheduler.Type.IO))
                    .subscribe(view::showListBerita, view::showError);
    }

    public interface View extends BenihPresenter.View {
        void showListBerita(List<Berita> listBerita);
    }
}
```

kemudian di activity atau fragmentnya kita bisa lakukan unsubcribe...

``` java
public class MainActivity extends BenihActivity implements BeritaPresenter.View {
    private BeritaPresenter beritaPresenter;

    @Override
    protected int getResourceLayout() {
        return R.layout.activity_main;
    }

    @Override
    protected void onViewReady(Bundle savedInstanceState) {
        beritaPresenter = new BeritaPresenter(this);
        Subscription loadBeritaRequest = beritaPresenter.loadListBerita();
        loadBeritaRequest.unsubscribe(); // Untuk membatalkan
    }

    @Override
    public void showListBerita(List<Berita> listBerita) {

    }

    @Override
    public void showError(Throwable throwable) {

    }
}
```

**Comment by choiruru** [comment]
Kemarin saya juga sudah nemu dari link ini
http://stackoverflow.com/questions/30727268/how-cancel-task-with-retrofit-and-rxjava
sama, pakai unsubsribe juga

terikamaksih atas tanggapannya. Ditunggu update Benihnya :smile:
